##YAML Template
---

logging:
  level: INFO
  loggers:
    com.udemy: DEBUG

secret: KhgDXDAxR8zGecDDjREQBcDATBxwBcbJ8HxUGZiECkPszoNuRPKnMpkDNCNdybMT

database:

  driverClass: org.postgresql.Driver

  user:  postgres

  password:  thomas881

  url: jdbc:postgresql://localhost:5432/iprwc

  properties:
    charSet: UTF-8

  maxWaitForConnection: 1s

  validationQuery: "/* HelloResource Health Check */ SELECT 1"

  validationQueryTimeout: 3s

  minSize: 8

  maxSize: 32

  checkConnectionWhileIdle: false

  evictionInterval: 10s

  minIdleTime: 1 minute